-- Migration: 002_create_ports
-- ทะเบียนเลข port สำหรับแสดงในหน้า Port

BEGIN;

CREATE TABLE IF NOT EXISTS ports (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  port_number   INTEGER      NOT NULL
                  CHECK (port_number >= 1 AND port_number <= 65535),
  project_name  VARCHAR(255) NOT NULL,
  description   TEXT,
  is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at    TIMESTAMPTZ
);

COMMENT ON TABLE  ports IS 'ทะเบียนเลข port ที่ใช้งานในระบบ พร้อมระบุว่าเป็นของ project ใด';
COMMENT ON COLUMN ports.id IS 'PK';
COMMENT ON COLUMN ports.port_number IS 'เลข port (1–65535) — unique เฉพาะแถวที่ยังไม่ลบ';
COMMENT ON COLUMN ports.project_name IS 'ชื่อ project ที่ใช้ port นี้';
COMMENT ON COLUMN ports.description IS 'รายละเอียดเพิ่มเติม เช่น service / หมายเหตุ';
COMMENT ON COLUMN ports.is_active IS 'สถานะเปิดใช้งาน port นี้';
COMMENT ON COLUMN ports.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN ports.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN ports.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS ports_port_number_active_uidx
  ON ports (port_number)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS ports_project_name_active_idx
  ON ports (project_name)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS ports_is_active_idx
  ON ports (is_active)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS ports_set_updated_at ON ports;
CREATE TRIGGER ports_set_updated_at
  BEFORE UPDATE ON ports
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

COMMIT;
