-- Migration: 003_create_projects
-- ทะเบียน project สำหรับแสดงในหน้า Projects (ผูก resource_types)

BEGIN;

CREATE TABLE IF NOT EXISTS projects (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              VARCHAR(255) NOT NULL,
  description       TEXT,
  resource_type_id  BIGINT       NOT NULL REFERENCES resource_types (id),
  is_active         BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at        TIMESTAMPTZ
);

COMMENT ON TABLE  projects IS 'ทะเบียน project พร้อมระบุประเภท resource';
COMMENT ON COLUMN projects.id IS 'PK';
COMMENT ON COLUMN projects.name IS 'ชื่อ project';
COMMENT ON COLUMN projects.description IS 'รายละเอียด project';
COMMENT ON COLUMN projects.resource_type_id IS 'FK → resource_types.id ประเภท resource ของ project';
COMMENT ON COLUMN projects.is_active IS 'สถานะเปิดใช้งาน project';
COMMENT ON COLUMN projects.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN projects.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN projects.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS projects_name_active_uidx
  ON projects (name)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS projects_resource_type_id_active_idx
  ON projects (resource_type_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS projects_is_active_idx
  ON projects (is_active)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS projects_set_updated_at ON projects;
CREATE TRIGGER projects_set_updated_at
  BEFORE UPDATE ON projects
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

COMMIT;
