-- 004_website_visits.sql
-- Daily aggregate visit counters for the public personal website

CREATE TABLE IF NOT EXISTS website_visits (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visit_date   DATE         NOT NULL,
  visit_count  BIGINT       NOT NULL DEFAULT 0
                 CHECK (visit_count >= 0),
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  CONSTRAINT website_visits_visit_date_uidx UNIQUE (visit_date)
);

COMMENT ON TABLE  website_visits IS 'ยอดเข้าชม personal website รวมรายวัน';
COMMENT ON COLUMN website_visits.id IS 'PK';
COMMENT ON COLUMN website_visits.visit_date IS 'วันที่นับยอด (1 แถวต่อ 1 วัน)';
COMMENT ON COLUMN website_visits.visit_count IS 'จำนวนครั้งที่เข้าชมในวันนั้น';
COMMENT ON COLUMN website_visits.created_at IS 'เวลาสร้างแถว';
COMMENT ON COLUMN website_visits.updated_at IS 'เวลาแก้ไขล่าสุด (อัปเดตเมื่อเพิ่มยอด)';

CREATE INDEX IF NOT EXISTS website_visits_visit_date_idx
  ON website_visits (visit_date DESC);

DROP TRIGGER IF EXISTS website_visits_set_updated_at ON website_visits;
CREATE TRIGGER website_visits_set_updated_at
  BEFORE UPDATE ON website_visits
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();
