-- Migration: 008_create_all_database
-- master ประเภท database / data store

BEGIN;

CREATE TABLE IF NOT EXISTS all_database (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        VARCHAR(64)  NOT NULL,
  name        VARCHAR(255) NOT NULL,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at  TIMESTAMPTZ
);

COMMENT ON TABLE  all_database IS 'master ประเภท database / data store ที่ระบบรองรับ';
COMMENT ON COLUMN all_database.id IS 'PK';
COMMENT ON COLUMN all_database.code IS 'รหัสสำหรับระบบ (unique เฉพาะแถวที่ยังไม่ลบ)';
COMMENT ON COLUMN all_database.name IS 'ชื่อที่แสดง';
COMMENT ON COLUMN all_database.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN all_database.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN all_database.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS all_database_code_active_uidx
  ON all_database (code)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS all_database_set_updated_at ON all_database;
CREATE TRIGGER all_database_set_updated_at
  BEFORE UPDATE ON all_database
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

INSERT INTO all_database (code, name)
SELECT seed.code, seed.name
FROM (
  VALUES
    ('postgres', 'PostgreSQL'),
    ('mysql', 'MySQL'),
    ('mongodb', 'MongoDB'),
    ('firebase', 'Firebase'),
    ('supabase', 'Supabase')
) AS seed(code, name)
WHERE NOT EXISTS (
  SELECT 1
  FROM all_database ad
  WHERE ad.code = seed.code
    AND ad.deleted_at IS NULL
);

COMMIT;
