-- Migration: 009_create_databases
-- ทะเบียน database instance ที่ใช้งานในระบบ

BEGIN;

CREATE TABLE IF NOT EXISTS databases (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              VARCHAR(255) NOT NULL,
  project_id        BIGINT       NOT NULL
                      REFERENCES projects (id),
  all_database_id   BIGINT       NOT NULL
                      REFERENCES all_database (id),
  description       TEXT,
  is_active         BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at        TIMESTAMPTZ
);

COMMENT ON TABLE  databases IS 'ทะเบียน database instance ที่ใช้งานในระบบ';
COMMENT ON COLUMN databases.id IS 'PK';
COMMENT ON COLUMN databases.name IS 'ชื่อ database / instance';
COMMENT ON COLUMN databases.project_id IS 'FK → projects.id project ที่ใช้ database นี้';
COMMENT ON COLUMN databases.all_database_id IS 'FK → all_database.id (ประเภท database)';
COMMENT ON COLUMN databases.description IS 'รายละเอียดเพิ่มเติม';
COMMENT ON COLUMN databases.is_active IS 'สถานะเปิดใช้งาน';
COMMENT ON COLUMN databases.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN databases.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN databases.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS databases_name_type_project_active_uidx
  ON databases (name, all_database_id, project_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS databases_project_id_active_idx
  ON databases (project_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS databases_all_database_id_active_idx
  ON databases (all_database_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS databases_is_active_idx
  ON databases (is_active)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS databases_set_updated_at ON databases;
CREATE TRIGGER databases_set_updated_at
  BEFORE UPDATE ON databases
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

COMMIT;
