-- Bann Laundry schema (admin tables)
-- Soft delete: deleted_at IS NULL = แถวยังใช้
-- Query ปกติทุกตาราง: WHERE deleted_at IS NULL
-- Unique ของอีเมล / code ใช้ partial index

BEGIN;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION set_updated_at() IS
  'อัปเดต updated_at อัตโนมัติทุกครั้งที่ UPDATE';

-- ---------------------------------------------------------------------------
-- admins
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admins (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email          VARCHAR(255) NOT NULL,
  display_name   VARCHAR(255) NOT NULL,
  role           VARCHAR(32)  NOT NULL DEFAULT 'staff'
                   CHECK (role IN ('owner', 'admin', 'staff')),
  last_login_at  TIMESTAMPTZ,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at     TIMESTAMPTZ
);

COMMENT ON TABLE  admins IS 'พนักงาน / ผู้ดูแลระบบ (ข้อมูลโปรไฟล์)';
COMMENT ON COLUMN admins.id IS 'PK';
COMMENT ON COLUMN admins.email IS 'อีเมล — unique เฉพาะแถวที่ยังไม่ลบ';
COMMENT ON COLUMN admins.display_name IS 'ชื่อที่แสดง';
COMMENT ON COLUMN admins.role IS 'owner | admin | staff';
COMMENT ON COLUMN admins.last_login_at IS 'เวลา login ล่าสุด — อัปเดตตอน login สำเร็จ';
COMMENT ON COLUMN admins.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admins.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admins.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admins_email_active_uidx
  ON admins (email)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admins_set_updated_at ON admins;
CREATE TRIGGER admins_set_updated_at
  BEFORE UPDATE ON admins
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- admin_auth
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_auth (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id       BIGINT       NOT NULL REFERENCES admins (id),
  password_hash  TEXT         NOT NULL,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at     TIMESTAMPTZ
);

COMMENT ON TABLE  admin_auth IS 'ข้อมูล auth ของ admin เช่น password hash';
COMMENT ON COLUMN admin_auth.id IS 'PK';
COMMENT ON COLUMN admin_auth.admin_id IS 'FK → admins.id (1 admin ต่อ 1 auth ที่ active)';
COMMENT ON COLUMN admin_auth.password_hash IS 'รหัสผ่านที่ hash แล้ว';
COMMENT ON COLUMN admin_auth.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_auth.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_auth.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_auth_admin_id_active_uidx
  ON admin_auth (admin_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_auth_set_updated_at ON admin_auth;
CREATE TRIGGER admin_auth_set_updated_at
  BEFORE UPDATE ON admin_auth
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- admin_log
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_log (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id     BIGINT       NOT NULL REFERENCES admins (id),
  action       VARCHAR(64)  NOT NULL,
  entity_type  VARCHAR(64),
  entity_id    BIGINT,
  message      TEXT,
  meta         JSONB,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at   TIMESTAMPTZ
);

COMMENT ON TABLE  admin_log IS 'ประวัติการใช้งานของ admin — โดยปกติ insert อย่างเดียว';
COMMENT ON COLUMN admin_log.id IS 'PK';
COMMENT ON COLUMN admin_log.admin_id IS 'FK → admins.id ผู้ทำรายการ';
COMMENT ON COLUMN admin_log.action IS 'ชนิดเหตุการณ์ เช่น login, create, update, soft_delete';
COMMENT ON COLUMN admin_log.entity_type IS 'ชนิดข้อมูลที่เกี่ยวกับ action เช่น order, user, list_price, admin';
COMMENT ON COLUMN admin_log.entity_id IS 'id ของข้อมูลที่เกี่ยวข้อง (nullable)';
COMMENT ON COLUMN admin_log.message IS 'ข้อความเพิ่มเติม';
COMMENT ON COLUMN admin_log.meta IS 'รายละเอียดเพิ่มเติมแบบ JSON (optional)';
COMMENT ON COLUMN admin_log.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_log.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_log.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE INDEX IF NOT EXISTS admin_log_admin_id_idx
  ON admin_log (admin_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_log_action_idx
  ON admin_log (action)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_log_entity_idx
  ON admin_log (entity_type, entity_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_log_created_at_idx
  ON admin_log (created_at DESC)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_log_set_updated_at ON admin_log;
CREATE TRIGGER admin_log_set_updated_at
  BEFORE UPDATE ON admin_log
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- admin_menu_label
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_menu_label (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code         VARCHAR(64)  NOT NULL,
  name         VARCHAR(255) NOT NULL,
  is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
  sort_order   INTEGER      NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at   TIMESTAMPTZ
);

COMMENT ON TABLE  admin_menu_label IS 'กลุ่ม label ของเมนูฝั่ง admin เช่น การจัดการข้อมูล, รายงาน';
COMMENT ON COLUMN admin_menu_label.id IS 'PK';
COMMENT ON COLUMN admin_menu_label.code IS 'รหัส label สำหรับระบบ (unique เฉพาะแถวที่ยังไม่ลบ)';
COMMENT ON COLUMN admin_menu_label.name IS 'ชื่อที่แสดงบนเมนู';
COMMENT ON COLUMN admin_menu_label.is_active IS 'สถานะเปิดใช้งาน label';
COMMENT ON COLUMN admin_menu_label.sort_order IS 'ลำดับการแสดงผล';
COMMENT ON COLUMN admin_menu_label.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_menu_label.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_menu_label.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_menu_label_code_active_uidx
  ON admin_menu_label (code)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_menu_label_set_updated_at ON admin_menu_label;
CREATE TRIGGER admin_menu_label_set_updated_at
  BEFORE UPDATE ON admin_menu_label
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

INSERT INTO admin_menu_label (code, name, is_active, sort_order)
SELECT seed.code, seed.name, TRUE, seed.sort_order
FROM (
  VALUES
    ('dashboard', 'Dashboard', 1),
    ('infrastructure', 'Infrastructure', 2),
    ('management', 'Management', 3),
    ('logs', 'Logs', 4)
) AS seed(code, name, sort_order)
WHERE NOT EXISTS (
  SELECT 1
  FROM admin_menu_label aml
  WHERE aml.code = seed.code
    AND aml.deleted_at IS NULL
);

-- ---------------------------------------------------------------------------
-- admin_menu_tab
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_menu_tab (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_label_id BIGINT       NOT NULL REFERENCES admin_menu_label (id),
  code          VARCHAR(64)  NOT NULL,
  name          VARCHAR(255) NOT NULL,
  is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
  sort_order    INTEGER      NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at    TIMESTAMPTZ
);

COMMENT ON TABLE  admin_menu_tab IS 'tab เมนูที่อยู่ภายใต้ label แต่ละกลุ่ม';
COMMENT ON COLUMN admin_menu_tab.id IS 'PK';
COMMENT ON COLUMN admin_menu_tab.menu_label_id IS 'FK → admin_menu_label.id';
COMMENT ON COLUMN admin_menu_tab.code IS 'รหัส tab สำหรับอ้างอิงสิทธิ์ (unique เฉพาะแถวที่ยังไม่ลบ)';
COMMENT ON COLUMN admin_menu_tab.name IS 'ชื่อ tab ที่แสดงบน UI';
COMMENT ON COLUMN admin_menu_tab.is_active IS 'สถานะเปิดใช้งาน tab';
COMMENT ON COLUMN admin_menu_tab.sort_order IS 'ลำดับการแสดงผลในกลุ่ม';
COMMENT ON COLUMN admin_menu_tab.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_menu_tab.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_menu_tab.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_menu_tab_code_active_uidx
  ON admin_menu_tab (code)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_menu_tab_label_id_idx
  ON admin_menu_tab (menu_label_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_menu_tab_set_updated_at ON admin_menu_tab;
CREATE TRIGGER admin_menu_tab_set_updated_at
  BEFORE UPDATE ON admin_menu_tab
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

INSERT INTO admin_menu_tab (menu_label_id, code, name, is_active, sort_order)
SELECT lbl.id, seed.code, seed.name, TRUE, seed.sort_order
FROM (
  VALUES
    ('dashboard', 'overview', 'Overview', 1),
    ('dashboard', 'bi', 'BI', 2),
    ('infrastructure', 'vps', 'VPS', 1),
    ('infrastructure', 'ci-cd', 'CI-CD', 2),
    ('infrastructure', 'port', 'Port', 3),
    ('infrastructure', 'domain', 'Domain', 4),
    ('infrastructure', 'database', 'Database', 5),
    ('management', 'projects', 'Projects', 1),
    ('management', 'admins', 'Admins', 2),
    ('logs', 'logs', 'Logs', 1)
) AS seed(label_code, code, name, sort_order)
INNER JOIN admin_menu_label lbl
  ON lbl.code = seed.label_code
 AND lbl.deleted_at IS NULL
WHERE NOT EXISTS (
  SELECT 1
  FROM admin_menu_tab amt
  WHERE amt.code = seed.code
    AND amt.deleted_at IS NULL
);

-- ---------------------------------------------------------------------------
-- admin_permission_action
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_permission_action (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code         VARCHAR(64)  NOT NULL,
  name         VARCHAR(255) NOT NULL,
  is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
  description  TEXT,
  sort_order   INTEGER      NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at   TIMESTAMPTZ
);

COMMENT ON TABLE  admin_permission_action IS 'master ของ action สิทธิ์ เช่น view/add/edit/delete/export';
COMMENT ON COLUMN admin_permission_action.id IS 'PK';
COMMENT ON COLUMN admin_permission_action.code IS 'รหัส action สำหรับระบบ (unique เฉพาะแถวที่ยังไม่ลบ)';
COMMENT ON COLUMN admin_permission_action.name IS 'ชื่อ action ที่แสดง';
COMMENT ON COLUMN admin_permission_action.is_active IS 'สถานะเปิดใช้งาน action';
COMMENT ON COLUMN admin_permission_action.description IS 'รายละเอียดเพิ่มเติม';
COMMENT ON COLUMN admin_permission_action.sort_order IS 'ลำดับการแสดงผล';
COMMENT ON COLUMN admin_permission_action.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_permission_action.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_permission_action.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_permission_action_code_active_uidx
  ON admin_permission_action (code)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_permission_action_set_updated_at ON admin_permission_action;
CREATE TRIGGER admin_permission_action_set_updated_at
  BEFORE UPDATE ON admin_permission_action
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

INSERT INTO admin_permission_action (code, name, description, sort_order)
SELECT seed.code, seed.name, seed.description, seed.sort_order
FROM (
  VALUES
    ('view', 'View', 'ดูข้อมูล', 1),
    ('add', 'Add', 'เพิ่มข้อมูล', 2),
    ('edit', 'Edit', 'แก้ไขข้อมูล', 3),
    ('delete', 'Delete', 'ลบข้อมูล', 4),
    ('export', 'Export', 'ส่งออกข้อมูล', 5)
) AS seed(code, name, description, sort_order)
WHERE NOT EXISTS (
  SELECT 1
  FROM admin_permission_action apa
  WHERE apa.code = seed.code
    AND apa.deleted_at IS NULL
);

-- ---------------------------------------------------------------------------
-- admin_menu_tab_action
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_menu_tab_action (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_tab_id           BIGINT       NOT NULL REFERENCES admin_menu_tab (id),
  permission_action_id  BIGINT       NOT NULL REFERENCES admin_permission_action (id),
  created_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at            TIMESTAMPTZ
);

COMMENT ON TABLE  admin_menu_tab_action IS 'mapping ว่า tab ใดรองรับ action ใดได้บ้าง';
COMMENT ON COLUMN admin_menu_tab_action.id IS 'PK';
COMMENT ON COLUMN admin_menu_tab_action.menu_tab_id IS 'FK → admin_menu_tab.id';
COMMENT ON COLUMN admin_menu_tab_action.permission_action_id IS 'FK → admin_permission_action.id';
COMMENT ON COLUMN admin_menu_tab_action.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_menu_tab_action.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_menu_tab_action.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_menu_tab_action_pair_active_uidx
  ON admin_menu_tab_action (menu_tab_id, permission_action_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_menu_tab_action_tab_id_idx
  ON admin_menu_tab_action (menu_tab_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_menu_tab_action_action_id_idx
  ON admin_menu_tab_action (permission_action_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_menu_tab_action_set_updated_at ON admin_menu_tab_action;
CREATE TRIGGER admin_menu_tab_action_set_updated_at
  BEFORE UPDATE ON admin_menu_tab_action
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

INSERT INTO admin_menu_tab_action (menu_tab_id, permission_action_id)
SELECT mt.id, pa.id
FROM (
  VALUES
    ('overview', 'view'),
    ('bi', 'view'),
    ('vps', 'view'),
    ('vps', 'add'),
    ('vps', 'edit'),
    ('vps', 'delete'),
    ('vps', 'export'),
    ('ci-cd', 'view'),
    ('ci-cd', 'add'),
    ('ci-cd', 'edit'),
    ('ci-cd', 'delete'),
    ('ci-cd', 'export'),
    ('port', 'view'),
    ('port', 'add'),
    ('port', 'edit'),
    ('port', 'delete'),
    ('port', 'export'),
    ('domain', 'view'),
    ('domain', 'add'),
    ('domain', 'edit'),
    ('domain', 'delete'),
    ('domain', 'export'),
    ('database', 'view'),
    ('database', 'add'),
    ('database', 'edit'),
    ('database', 'delete'),
    ('database', 'export'),
    ('projects', 'view'),
    ('projects', 'add'),
    ('projects', 'edit'),
    ('projects', 'delete'),
    ('projects', 'export'),
    ('admins', 'view'),
    ('admins', 'add'),
    ('admins', 'edit'),
    ('admins', 'delete'),
    ('admins', 'export'),
    ('logs', 'view')
) AS seed(tab_code, action_code)
INNER JOIN admin_menu_tab mt
  ON mt.code = seed.tab_code
 AND mt.deleted_at IS NULL
INNER JOIN admin_permission_action pa
  ON pa.code = seed.action_code
 AND pa.deleted_at IS NULL
WHERE NOT EXISTS (
  SELECT 1
  FROM admin_menu_tab_action mta
  WHERE mta.menu_tab_id = mt.id
    AND mta.permission_action_id = pa.id
    AND mta.deleted_at IS NULL
);

-- ---------------------------------------------------------------------------
-- admin_permissions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_permissions (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id            BIGINT       NOT NULL REFERENCES admins (id),
  menu_tab_action_id  BIGINT       NOT NULL REFERENCES admin_menu_tab_action (id),
  is_allowed          BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at          TIMESTAMPTZ
);

COMMENT ON TABLE  admin_permissions IS 'สิทธิ์ราย admin ว่าอนุญาต action ใดใน tab ไหน';
COMMENT ON COLUMN admin_permissions.id IS 'PK';
COMMENT ON COLUMN admin_permissions.admin_id IS 'FK → admins.id';
COMMENT ON COLUMN admin_permissions.menu_tab_action_id IS 'FK → admin_menu_tab_action.id';
COMMENT ON COLUMN admin_permissions.is_allowed IS 'true = อนุญาต, false = ปฏิเสธ';
COMMENT ON COLUMN admin_permissions.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_permissions.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_permissions.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_permissions_admin_action_active_uidx
  ON admin_permissions (admin_id, menu_tab_action_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_permissions_admin_id_idx
  ON admin_permissions (admin_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_permissions_menu_tab_action_id_idx
  ON admin_permissions (menu_tab_action_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_permissions_set_updated_at ON admin_permissions;
CREATE TRIGGER admin_permissions_set_updated_at
  BEFORE UPDATE ON admin_permissions
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- resource_types
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS resource_types (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code         VARCHAR(64)  NOT NULL,
  name         VARCHAR(255) NOT NULL,
  description  TEXT,
  is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at   TIMESTAMPTZ
);

COMMENT ON TABLE  resource_types IS 'master ของประเภท resource เช่น Frontend / Backend / Database / Services';
COMMENT ON COLUMN resource_types.id IS 'PK';
COMMENT ON COLUMN resource_types.code IS 'รหัสประเภทสำหรับระบบ (unique เฉพาะแถวที่ยังไม่ลบ)';
COMMENT ON COLUMN resource_types.name IS 'ชื่อประเภทที่แสดง';
COMMENT ON COLUMN resource_types.description IS 'รายละเอียดเพิ่มเติม';
COMMENT ON COLUMN resource_types.is_active IS 'สถานะเปิดใช้งาน';
COMMENT ON COLUMN resource_types.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN resource_types.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN resource_types.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS resource_types_code_active_uidx
  ON resource_types (code)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS resource_types_set_updated_at ON resource_types;
CREATE TRIGGER resource_types_set_updated_at
  BEFORE UPDATE ON resource_types
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

INSERT INTO resource_types (code, name, description, is_active)
SELECT seed.code, seed.name, seed.description, TRUE
FROM (
  VALUES
    ('frontend', 'Frontend', 'UI / client-side application'),
    ('backend', 'Backend', 'API / server-side application'),
    ('database', 'Database', 'ฐานข้อมูล / data store'),
    ('services', 'Services', 'บริการภายนอก / third-party services')
) AS seed(code, name, description)
WHERE NOT EXISTS (
  SELECT 1
  FROM resource_types rt
  WHERE rt.code = seed.code
    AND rt.deleted_at IS NULL
);

-- ---------------------------------------------------------------------------
-- projects
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS projects (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              VARCHAR(255) NOT NULL,
  description       TEXT,
  type              VARCHAR(32)  NOT NULL DEFAULT 'project'
                      CHECK (type IN ('project', 'service')),
  resource_type_id  BIGINT       NOT NULL REFERENCES resource_types (id),
  is_active         BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at        TIMESTAMPTZ
);

COMMENT ON TABLE  projects IS 'ทะเบียน project/service พร้อมระบุประเภท resource';
COMMENT ON COLUMN projects.id IS 'PK';
COMMENT ON COLUMN projects.name IS 'ชื่อ project / service';
COMMENT ON COLUMN projects.description IS 'รายละเอียด';
COMMENT ON COLUMN projects.type IS 'ชนิดรายการ: project | service';
COMMENT ON COLUMN projects.resource_type_id IS 'FK → resource_types.id ประเภท resource';
COMMENT ON COLUMN projects.is_active IS 'สถานะเปิดใช้งาน';
COMMENT ON COLUMN projects.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN projects.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN projects.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS projects_name_active_uidx
  ON projects (name)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS projects_type_active_idx
  ON projects (type)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS projects_resource_type_id_active_idx
  ON projects (resource_type_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS projects_is_active_idx
  ON projects (is_active)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS projects_set_updated_at ON projects;
CREATE TRIGGER projects_set_updated_at
  BEFORE UPDATE ON projects
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- ports
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ports (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  port_number       INTEGER      NOT NULL
                      CHECK (port_number >= 1 AND port_number <= 65535),
  project_id        BIGINT       NOT NULL REFERENCES projects (id),
  resource_type_id  BIGINT       NOT NULL REFERENCES resource_types (id),
  description       TEXT,
  is_active         BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at        TIMESTAMPTZ
);

COMMENT ON TABLE  ports IS 'ทะเบียนเลข port ที่ใช้งานในระบบ พร้อมระบุ project และ resource type';
COMMENT ON COLUMN ports.id IS 'PK';
COMMENT ON COLUMN ports.port_number IS 'เลข port (1–65535) — unique เฉพาะแถวที่ยังไม่ลบ';
COMMENT ON COLUMN ports.project_id IS 'FK → projects.id — unique คู่กับ resource_type_id เฉพาะแถวที่ยังไม่ลบ';
COMMENT ON COLUMN ports.resource_type_id IS 'FK → resource_types.id ประเภท resource ของ port';
COMMENT ON COLUMN ports.description IS 'รายละเอียดเพิ่มเติม เช่น service / หมายเหตุ';
COMMENT ON COLUMN ports.is_active IS 'สถานะเปิดใช้งาน port นี้';
COMMENT ON COLUMN ports.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN ports.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN ports.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS ports_port_number_active_uidx
  ON ports (port_number)
  WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ports_project_resource_type_active_uidx
  ON ports (project_id, resource_type_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS ports_project_id_active_idx
  ON ports (project_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS ports_resource_type_id_active_idx
  ON ports (resource_type_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS ports_is_active_idx
  ON ports (is_active)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS ports_set_updated_at ON ports;
CREATE TRIGGER ports_set_updated_at
  BEFORE UPDATE ON ports
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- all_database
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS all_database (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        VARCHAR(64)  NOT NULL,
  name        VARCHAR(255) NOT NULL,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at  TIMESTAMPTZ
);

COMMENT ON TABLE  all_database IS 'master ประเภท database / data store ที่ระบบรองรับ';
COMMENT ON COLUMN all_database.id IS 'PK';
COMMENT ON COLUMN all_database.code IS 'รหัสสำหรับระบบ (unique เฉพาะแถวที่ยังไม่ลบ)';
COMMENT ON COLUMN all_database.name IS 'ชื่อที่แสดง';
COMMENT ON COLUMN all_database.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN all_database.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN all_database.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS all_database_code_active_uidx
  ON all_database (code)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS all_database_set_updated_at ON all_database;
CREATE TRIGGER all_database_set_updated_at
  BEFORE UPDATE ON all_database
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

INSERT INTO all_database (code, name)
SELECT seed.code, seed.name
FROM (
  VALUES
    ('postgres', 'PostgreSQL'),
    ('mysql', 'MySQL'),
    ('mongodb', 'MongoDB'),
    ('firebase', 'Firebase'),
    ('supabase', 'Supabase')
) AS seed(code, name)
WHERE NOT EXISTS (
  SELECT 1
  FROM all_database ad
  WHERE ad.code = seed.code
    AND ad.deleted_at IS NULL
);

-- ---------------------------------------------------------------------------
-- databases
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS databases (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              VARCHAR(255) NOT NULL,
  project_id        BIGINT       NOT NULL
                      REFERENCES projects (id),
  all_database_id   BIGINT       NOT NULL
                      REFERENCES all_database (id),
  description       TEXT,
  is_active         BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at        TIMESTAMPTZ
);

COMMENT ON TABLE  databases IS 'ทะเบียน database instance ที่ใช้งานในระบบ';
COMMENT ON COLUMN databases.id IS 'PK';
COMMENT ON COLUMN databases.name IS 'ชื่อ database / instance';
COMMENT ON COLUMN databases.project_id IS 'FK → projects.id project ที่ใช้ database นี้';
COMMENT ON COLUMN databases.all_database_id IS 'FK → all_database.id (ประเภท database)';
COMMENT ON COLUMN databases.description IS 'รายละเอียดเพิ่มเติม';
COMMENT ON COLUMN databases.is_active IS 'สถานะเปิดใช้งาน';
COMMENT ON COLUMN databases.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN databases.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN databases.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS databases_name_type_project_active_uidx
  ON databases (name, all_database_id, project_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS databases_project_id_active_idx
  ON databases (project_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS databases_all_database_id_active_idx
  ON databases (all_database_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS databases_is_active_idx
  ON databases (is_active)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS databases_set_updated_at ON databases;
CREATE TRIGGER databases_set_updated_at
  BEFORE UPDATE ON databases
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

COMMIT;
