-- Bann Laundry schema (admin tables)
-- Soft delete: deleted_at IS NULL = แถวยังใช้
-- Query ปกติทุกตาราง: WHERE deleted_at IS NULL
-- Unique ของอีเมล / code ใช้ partial index

BEGIN;

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION set_updated_at() IS
  'อัปเดต updated_at อัตโนมัติทุกครั้งที่ UPDATE';

-- ---------------------------------------------------------------------------
-- admins
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admins (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email          VARCHAR(255) NOT NULL,
  display_name   VARCHAR(255) NOT NULL,
  role           VARCHAR(32)  NOT NULL DEFAULT 'staff'
                   CHECK (role IN ('owner', 'admin', 'staff')),
  last_login_at  TIMESTAMPTZ,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at     TIMESTAMPTZ
);

COMMENT ON TABLE  admins IS 'พนักงาน / ผู้ดูแลระบบ (ข้อมูลโปรไฟล์)';
COMMENT ON COLUMN admins.id IS 'PK';
COMMENT ON COLUMN admins.email IS 'อีเมล — unique เฉพาะแถวที่ยังไม่ลบ';
COMMENT ON COLUMN admins.display_name IS 'ชื่อที่แสดง';
COMMENT ON COLUMN admins.role IS 'owner | admin | staff';
COMMENT ON COLUMN admins.last_login_at IS 'เวลา login ล่าสุด — อัปเดตตอน login สำเร็จ';
COMMENT ON COLUMN admins.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admins.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admins.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admins_email_active_uidx
  ON admins (email)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admins_set_updated_at ON admins;
CREATE TRIGGER admins_set_updated_at
  BEFORE UPDATE ON admins
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- admin_auth
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_auth (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id       BIGINT       NOT NULL REFERENCES admins (id),
  password_hash  TEXT         NOT NULL,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at     TIMESTAMPTZ
);

COMMENT ON TABLE  admin_auth IS 'ข้อมูล auth ของ admin เช่น password hash';
COMMENT ON COLUMN admin_auth.id IS 'PK';
COMMENT ON COLUMN admin_auth.admin_id IS 'FK → admins.id (1 admin ต่อ 1 auth ที่ active)';
COMMENT ON COLUMN admin_auth.password_hash IS 'รหัสผ่านที่ hash แล้ว';
COMMENT ON COLUMN admin_auth.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_auth.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_auth.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_auth_admin_id_active_uidx
  ON admin_auth (admin_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_auth_set_updated_at ON admin_auth;
CREATE TRIGGER admin_auth_set_updated_at
  BEFORE UPDATE ON admin_auth
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- admin_log
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_log (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id     BIGINT       NOT NULL REFERENCES admins (id),
  action       VARCHAR(64)  NOT NULL,
  entity_type  VARCHAR(64),
  entity_id    BIGINT,
  message      TEXT,
  meta         JSONB,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at   TIMESTAMPTZ
);

COMMENT ON TABLE  admin_log IS 'ประวัติการใช้งานของ admin — โดยปกติ insert อย่างเดียว';
COMMENT ON COLUMN admin_log.id IS 'PK';
COMMENT ON COLUMN admin_log.admin_id IS 'FK → admins.id ผู้ทำรายการ';
COMMENT ON COLUMN admin_log.action IS 'ชนิดเหตุการณ์ เช่น login, create, update, soft_delete';
COMMENT ON COLUMN admin_log.entity_type IS 'ชนิดข้อมูลที่เกี่ยวกับ action เช่น order, user, list_price, admin';
COMMENT ON COLUMN admin_log.entity_id IS 'id ของข้อมูลที่เกี่ยวข้อง (nullable)';
COMMENT ON COLUMN admin_log.message IS 'ข้อความเพิ่มเติม';
COMMENT ON COLUMN admin_log.meta IS 'รายละเอียดเพิ่มเติมแบบ JSON (optional)';
COMMENT ON COLUMN admin_log.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_log.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_log.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE INDEX IF NOT EXISTS admin_log_admin_id_idx
  ON admin_log (admin_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_log_action_idx
  ON admin_log (action)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_log_entity_idx
  ON admin_log (entity_type, entity_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_log_created_at_idx
  ON admin_log (created_at DESC)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_log_set_updated_at ON admin_log;
CREATE TRIGGER admin_log_set_updated_at
  BEFORE UPDATE ON admin_log
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- admin_menu_label
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_menu_label (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code         VARCHAR(64)  NOT NULL,
  name         VARCHAR(255) NOT NULL,
  is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
  sort_order   INTEGER      NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at   TIMESTAMPTZ
);

COMMENT ON TABLE  admin_menu_label IS 'กลุ่ม label ของเมนูฝั่ง admin เช่น การจัดการข้อมูล, รายงาน';
COMMENT ON COLUMN admin_menu_label.id IS 'PK';
COMMENT ON COLUMN admin_menu_label.code IS 'รหัส label สำหรับระบบ (unique เฉพาะแถวที่ยังไม่ลบ)';
COMMENT ON COLUMN admin_menu_label.name IS 'ชื่อที่แสดงบนเมนู';
COMMENT ON COLUMN admin_menu_label.is_active IS 'สถานะเปิดใช้งาน label';
COMMENT ON COLUMN admin_menu_label.sort_order IS 'ลำดับการแสดงผล';
COMMENT ON COLUMN admin_menu_label.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_menu_label.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_menu_label.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_menu_label_code_active_uidx
  ON admin_menu_label (code)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_menu_label_set_updated_at ON admin_menu_label;
CREATE TRIGGER admin_menu_label_set_updated_at
  BEFORE UPDATE ON admin_menu_label
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

INSERT INTO admin_menu_label (code, name, is_active, sort_order)
SELECT seed.code, seed.name, TRUE, seed.sort_order
FROM (
  VALUES
    ('dashboard', 'Dashboard', 1),
    ('content', 'Content', 2),
    ('management', 'Management', 3),
    ('logs', 'Logs', 4)
) AS seed(code, name, sort_order)
WHERE NOT EXISTS (
  SELECT 1
  FROM admin_menu_label aml
  WHERE aml.code = seed.code
    AND aml.deleted_at IS NULL
);

-- ---------------------------------------------------------------------------
-- admin_menu_tab
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_menu_tab (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_label_id BIGINT       NOT NULL REFERENCES admin_menu_label (id),
  code          VARCHAR(64)  NOT NULL,
  name          VARCHAR(255) NOT NULL,
  is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
  sort_order    INTEGER      NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at    TIMESTAMPTZ
);

COMMENT ON TABLE  admin_menu_tab IS 'tab เมนูที่อยู่ภายใต้ label แต่ละกลุ่ม';
COMMENT ON COLUMN admin_menu_tab.id IS 'PK';
COMMENT ON COLUMN admin_menu_tab.menu_label_id IS 'FK → admin_menu_label.id';
COMMENT ON COLUMN admin_menu_tab.code IS 'รหัส tab สำหรับอ้างอิงสิทธิ์ (unique เฉพาะแถวที่ยังไม่ลบ)';
COMMENT ON COLUMN admin_menu_tab.name IS 'ชื่อ tab ที่แสดงบน UI';
COMMENT ON COLUMN admin_menu_tab.is_active IS 'สถานะเปิดใช้งาน tab';
COMMENT ON COLUMN admin_menu_tab.sort_order IS 'ลำดับการแสดงผลในกลุ่ม';
COMMENT ON COLUMN admin_menu_tab.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_menu_tab.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_menu_tab.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_menu_tab_code_active_uidx
  ON admin_menu_tab (code)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_menu_tab_label_id_idx
  ON admin_menu_tab (menu_label_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_menu_tab_set_updated_at ON admin_menu_tab;
CREATE TRIGGER admin_menu_tab_set_updated_at
  BEFORE UPDATE ON admin_menu_tab
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

INSERT INTO admin_menu_tab (menu_label_id, code, name, is_active, sort_order)
SELECT lbl.id, seed.code, seed.name, TRUE, seed.sort_order
FROM (
  VALUES
    ('dashboard', 'overview', 'Overview', 1),
    ('dashboard', 'bi', 'BI', 2),
    ('content', 'home-banners', 'Home Banners', 1),
    ('content', 'skills', 'Skills', 2),
    ('content', 'projects', 'Projects', 3),
    ('content', 'experiences', 'Experiences', 4),
    ('content', 'education', 'Education', 5),
    ('management', 'admins', 'Admins', 1),
    ('logs', 'logs', 'Logs', 1)
) AS seed(label_code, code, name, sort_order)
INNER JOIN admin_menu_label lbl
  ON lbl.code = seed.label_code
 AND lbl.deleted_at IS NULL
WHERE NOT EXISTS (
  SELECT 1
  FROM admin_menu_tab amt
  WHERE amt.code = seed.code
    AND amt.deleted_at IS NULL
);

-- ---------------------------------------------------------------------------
-- admin_permission_action
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_permission_action (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code         VARCHAR(64)  NOT NULL,
  name         VARCHAR(255) NOT NULL,
  is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
  description  TEXT,
  sort_order   INTEGER      NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at   TIMESTAMPTZ
);

COMMENT ON TABLE  admin_permission_action IS 'master ของ action สิทธิ์ เช่น view/add/edit/delete/export';
COMMENT ON COLUMN admin_permission_action.id IS 'PK';
COMMENT ON COLUMN admin_permission_action.code IS 'รหัส action สำหรับระบบ (unique เฉพาะแถวที่ยังไม่ลบ)';
COMMENT ON COLUMN admin_permission_action.name IS 'ชื่อ action ที่แสดง';
COMMENT ON COLUMN admin_permission_action.is_active IS 'สถานะเปิดใช้งาน action';
COMMENT ON COLUMN admin_permission_action.description IS 'รายละเอียดเพิ่มเติม';
COMMENT ON COLUMN admin_permission_action.sort_order IS 'ลำดับการแสดงผล';
COMMENT ON COLUMN admin_permission_action.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_permission_action.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_permission_action.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_permission_action_code_active_uidx
  ON admin_permission_action (code)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_permission_action_set_updated_at ON admin_permission_action;
CREATE TRIGGER admin_permission_action_set_updated_at
  BEFORE UPDATE ON admin_permission_action
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

INSERT INTO admin_permission_action (code, name, description, sort_order)
SELECT seed.code, seed.name, seed.description, seed.sort_order
FROM (
  VALUES
    ('view', 'View', 'ดูข้อมูล', 1),
    ('add', 'Add', 'เพิ่มข้อมูล', 2),
    ('edit', 'Edit', 'แก้ไขข้อมูล', 3),
    ('delete', 'Delete', 'ลบข้อมูล', 4),
    ('export', 'Export', 'ส่งออกข้อมูล', 5)
) AS seed(code, name, description, sort_order)
WHERE NOT EXISTS (
  SELECT 1
  FROM admin_permission_action apa
  WHERE apa.code = seed.code
    AND apa.deleted_at IS NULL
);

-- ---------------------------------------------------------------------------
-- admin_menu_tab_action
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_menu_tab_action (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_tab_id           BIGINT       NOT NULL REFERENCES admin_menu_tab (id),
  permission_action_id  BIGINT       NOT NULL REFERENCES admin_permission_action (id),
  created_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at            TIMESTAMPTZ
);

COMMENT ON TABLE  admin_menu_tab_action IS 'mapping ว่า tab ใดรองรับ action ใดได้บ้าง';
COMMENT ON COLUMN admin_menu_tab_action.id IS 'PK';
COMMENT ON COLUMN admin_menu_tab_action.menu_tab_id IS 'FK → admin_menu_tab.id';
COMMENT ON COLUMN admin_menu_tab_action.permission_action_id IS 'FK → admin_permission_action.id';
COMMENT ON COLUMN admin_menu_tab_action.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_menu_tab_action.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_menu_tab_action.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_menu_tab_action_pair_active_uidx
  ON admin_menu_tab_action (menu_tab_id, permission_action_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_menu_tab_action_tab_id_idx
  ON admin_menu_tab_action (menu_tab_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_menu_tab_action_action_id_idx
  ON admin_menu_tab_action (permission_action_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_menu_tab_action_set_updated_at ON admin_menu_tab_action;
CREATE TRIGGER admin_menu_tab_action_set_updated_at
  BEFORE UPDATE ON admin_menu_tab_action
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

INSERT INTO admin_menu_tab_action (menu_tab_id, permission_action_id)
SELECT mt.id, pa.id
FROM (
  VALUES
    ('overview', 'view'),
    ('bi', 'view'),
    ('home-banners', 'view'),
    ('home-banners', 'add'),
    ('home-banners', 'edit'),
    ('home-banners', 'delete'),
    ('home-banners', 'export'),
    ('skills', 'view'),
    ('skills', 'add'),
    ('skills', 'edit'),
    ('skills', 'delete'),
    ('skills', 'export'),
    ('projects', 'view'),
    ('projects', 'add'),
    ('projects', 'edit'),
    ('projects', 'delete'),
    ('projects', 'export'),
    ('experiences', 'view'),
    ('experiences', 'add'),
    ('experiences', 'edit'),
    ('experiences', 'delete'),
    ('experiences', 'export'),
    ('education', 'view'),
    ('education', 'add'),
    ('education', 'edit'),
    ('education', 'delete'),
    ('education', 'export'),
    ('admins', 'view'),
    ('admins', 'add'),
    ('admins', 'edit'),
    ('admins', 'delete'),
    ('admins', 'export'),
    ('logs', 'view')
) AS seed(tab_code, action_code)
INNER JOIN admin_menu_tab mt
  ON mt.code = seed.tab_code
 AND mt.deleted_at IS NULL
INNER JOIN admin_permission_action pa
  ON pa.code = seed.action_code
 AND pa.deleted_at IS NULL
WHERE NOT EXISTS (
  SELECT 1
  FROM admin_menu_tab_action mta
  WHERE mta.menu_tab_id = mt.id
    AND mta.permission_action_id = pa.id
    AND mta.deleted_at IS NULL
);

-- ---------------------------------------------------------------------------
-- admin_permissions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_permissions (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id            BIGINT       NOT NULL REFERENCES admins (id),
  menu_tab_action_id  BIGINT       NOT NULL REFERENCES admin_menu_tab_action (id),
  is_allowed          BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at          TIMESTAMPTZ
);

COMMENT ON TABLE  admin_permissions IS 'สิทธิ์ราย admin ว่าอนุญาต action ใดใน tab ไหน';
COMMENT ON COLUMN admin_permissions.id IS 'PK';
COMMENT ON COLUMN admin_permissions.admin_id IS 'FK → admins.id';
COMMENT ON COLUMN admin_permissions.menu_tab_action_id IS 'FK → admin_menu_tab_action.id';
COMMENT ON COLUMN admin_permissions.is_allowed IS 'true = อนุญาต, false = ปฏิเสธ';
COMMENT ON COLUMN admin_permissions.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN admin_permissions.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN admin_permissions.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS admin_permissions_admin_action_active_uidx
  ON admin_permissions (admin_id, menu_tab_action_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_permissions_admin_id_idx
  ON admin_permissions (admin_id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS admin_permissions_menu_tab_action_id_idx
  ON admin_permissions (menu_tab_action_id)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS admin_permissions_set_updated_at ON admin_permissions;
CREATE TRIGGER admin_permissions_set_updated_at
  BEFORE UPDATE ON admin_permissions
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- home_banners
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS home_banners (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR(255) NOT NULL,
  media_type     VARCHAR(32)  NOT NULL
                   CHECK (media_type IN ('image', 'video')),
  url            TEXT         NOT NULL,
  display_order  INTEGER      NOT NULL DEFAULT 0,
  is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at     TIMESTAMPTZ
);

COMMENT ON TABLE  home_banners IS 'แบนเนอร์หน้าแรกของ personal website';
COMMENT ON COLUMN home_banners.id IS 'PK';
COMMENT ON COLUMN home_banners.name IS 'ชื่อแบนเนอร์สำหรับอ้างอิงในแอดมิน';
COMMENT ON COLUMN home_banners.media_type IS 'ชนิดสื่อ: image | video';
COMMENT ON COLUMN home_banners.url IS 'URL ของไฟล์สื่อ / path ที่อัปโหลด';
COMMENT ON COLUMN home_banners.display_order IS 'ลำดับการแสดงผล (น้อย = ก่อน)';
COMMENT ON COLUMN home_banners.is_active IS 'สถานะเปิดใช้งาน';
COMMENT ON COLUMN home_banners.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN home_banners.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN home_banners.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE INDEX IF NOT EXISTS home_banners_display_order_active_idx
  ON home_banners (display_order, id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS home_banners_is_active_idx
  ON home_banners (is_active)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS home_banners_set_updated_at ON home_banners;
CREATE TRIGGER home_banners_set_updated_at
  BEFORE UPDATE ON home_banners
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- skills
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS skills (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           VARCHAR(255) NOT NULL,
  media_type     VARCHAR(32)  NOT NULL
                   CHECK (media_type = 'image'),
  url            TEXT         NOT NULL,
  display_order  INTEGER      NOT NULL DEFAULT 0,
  is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at     TIMESTAMPTZ
);

COMMENT ON TABLE  skills IS 'ทักษะ / เทคโนโลยีที่แสดงบน personal website';
COMMENT ON COLUMN skills.id IS 'PK';
COMMENT ON COLUMN skills.name IS 'ชื่อทักษะ เช่น React, PostgreSQL';
COMMENT ON COLUMN skills.media_type IS 'ชนิดสื่อ: image เท่านั้น';
COMMENT ON COLUMN skills.url IS 'URL ของรูป / path ที่อัปโหลด';
COMMENT ON COLUMN skills.display_order IS 'ลำดับการแสดงผล (น้อย = ก่อน)';
COMMENT ON COLUMN skills.is_active IS 'สถานะเปิดใช้งาน';
COMMENT ON COLUMN skills.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN skills.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN skills.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE UNIQUE INDEX IF NOT EXISTS skills_name_active_uidx
  ON skills (name)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS skills_display_order_active_idx
  ON skills (display_order, id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS skills_is_active_idx
  ON skills (is_active)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS skills_set_updated_at ON skills;
CREATE TRIGGER skills_set_updated_at
  BEFORE UPDATE ON skills
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- projects
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS projects (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_th          VARCHAR(255) NOT NULL,
  name_en          VARCHAR(255) NOT NULL,
  description_th   TEXT,
  description_en   TEXT,
  thumbnail_url    TEXT,
  github_url       TEXT,
  demo_url         TEXT,
  display_order    INTEGER      NOT NULL DEFAULT 0,
  is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at       TIMESTAMPTZ
);

COMMENT ON TABLE  projects IS 'ผลงาน / โปรเจกต์บน personal website';
COMMENT ON COLUMN projects.id IS 'PK';
COMMENT ON COLUMN projects.name_th IS 'ชื่อโปรเจกต์ภาษาไทย';
COMMENT ON COLUMN projects.name_en IS 'ชื่อโปรเจกต์ภาษาอังกฤษ';
COMMENT ON COLUMN projects.description_th IS 'รายละเอียดภาษาไทย — TEXT สำหรับ Rich Text Editor (HTML/string)';
COMMENT ON COLUMN projects.description_en IS 'รายละเอียดภาษาอังกฤษ — TEXT สำหรับ Rich Text Editor (HTML/string)';
COMMENT ON COLUMN projects.thumbnail_url IS 'URL รูป thumbnail';
COMMENT ON COLUMN projects.github_url IS 'ลิงก์ GitHub (nullable)';
COMMENT ON COLUMN projects.demo_url IS 'ลิงก์ demo / live site (nullable)';
COMMENT ON COLUMN projects.display_order IS 'ลำดับการแสดงผล (น้อย = ก่อน)';
COMMENT ON COLUMN projects.is_active IS 'สถานะเปิดใช้งาน';
COMMENT ON COLUMN projects.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN projects.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN projects.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE INDEX IF NOT EXISTS projects_display_order_active_idx
  ON projects (display_order, id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS projects_is_active_idx
  ON projects (is_active)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS projects_set_updated_at ON projects;
CREATE TRIGGER projects_set_updated_at
  BEFORE UPDATE ON projects
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- experiences
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS experiences (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_th          VARCHAR(255) NOT NULL,
  name_en          VARCHAR(255) NOT NULL,
  description_th   TEXT,
  description_en   TEXT,
  position         VARCHAR(255) NOT NULL,
  start_date       DATE         NOT NULL,
  end_date         DATE,
  media_type       VARCHAR(32)
                     CHECK (media_type IS NULL OR media_type IN ('image', 'video')),
  url              TEXT,
  is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at       TIMESTAMPTZ,
  CONSTRAINT experiences_end_date_check
    CHECK (end_date IS NULL OR end_date >= start_date)
);

COMMENT ON TABLE  experiences IS 'ประวัติการทำงาน / ประสบการณ์';
COMMENT ON COLUMN experiences.id IS 'PK';
COMMENT ON COLUMN experiences.name_th IS 'ชื่อบริษัท / องค์กร ภาษาไทย';
COMMENT ON COLUMN experiences.name_en IS 'ชื่อบริษัท / องค์กร ภาษาอังกฤษ';
COMMENT ON COLUMN experiences.description_th IS 'รายละเอียดงานภาษาไทย — TEXT สำหรับ Rich Text Editor';
COMMENT ON COLUMN experiences.description_en IS 'รายละเอียดงานภาษาอังกฤษ — TEXT สำหรับ Rich Text Editor';
COMMENT ON COLUMN experiences.position IS 'ตำแหน่งงาน';
COMMENT ON COLUMN experiences.start_date IS 'วันเริ่มงาน';
COMMENT ON COLUMN experiences.end_date IS 'วันสิ้นสุดงาน — NULL = ปัจจุบัน';
COMMENT ON COLUMN experiences.media_type IS 'ชนิดสื่อโลโก้: image | video (nullable)';
COMMENT ON COLUMN experiences.url IS 'URL โลโก้ / สื่อ (nullable)';
COMMENT ON COLUMN experiences.is_active IS 'สถานะเปิดใช้งาน';
COMMENT ON COLUMN experiences.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN experiences.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN experiences.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE INDEX IF NOT EXISTS experiences_start_date_active_idx
  ON experiences (start_date DESC, id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS experiences_is_active_idx
  ON experiences (is_active)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS experiences_set_updated_at ON experiences;
CREATE TRIGGER experiences_set_updated_at
  BEFORE UPDATE ON experiences
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- education
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS education (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_th          VARCHAR(255) NOT NULL,
  name_en          VARCHAR(255) NOT NULL,
  description_th   TEXT,
  description_en   TEXT,
  start_date       DATE         NOT NULL,
  end_date         DATE,
  media_type       VARCHAR(32)
                     CHECK (media_type IS NULL OR media_type IN ('image', 'video')),
  url              TEXT,
  is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  deleted_at       TIMESTAMPTZ,
  CONSTRAINT education_end_date_check
    CHECK (end_date IS NULL OR end_date >= start_date)
);

COMMENT ON TABLE  education IS 'ประวัติการศึกษา';
COMMENT ON COLUMN education.id IS 'PK';
COMMENT ON COLUMN education.name_th IS 'ชื่อสถานศึกษา / หลักสูตร ภาษาไทย';
COMMENT ON COLUMN education.name_en IS 'ชื่อสถานศึกษา / หลักสูตร ภาษาอังกฤษ';
COMMENT ON COLUMN education.description_th IS 'รายละเอียดภาษาไทย — TEXT สำหรับ Rich Text Editor';
COMMENT ON COLUMN education.description_en IS 'รายละเอียดภาษาอังกฤษ — TEXT สำหรับ Rich Text Editor';
COMMENT ON COLUMN education.start_date IS 'วันเริ่มศึกษา';
COMMENT ON COLUMN education.end_date IS 'วันจบการศึกษา — NULL = กำลังศึกษา';
COMMENT ON COLUMN education.media_type IS 'ชนิดสื่อโลโก้: image | video (nullable)';
COMMENT ON COLUMN education.url IS 'URL โลโก้ / สื่อ (nullable)';
COMMENT ON COLUMN education.is_active IS 'สถานะเปิดใช้งาน';
COMMENT ON COLUMN education.created_at IS 'เวลาสร้าง';
COMMENT ON COLUMN education.updated_at IS 'เวลาแก้ไขล่าสุด';
COMMENT ON COLUMN education.deleted_at IS 'NULL = ยังใช้, มีค่า = soft delete';

CREATE INDEX IF NOT EXISTS education_start_date_active_idx
  ON education (start_date DESC, id)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS education_is_active_idx
  ON education (is_active)
  WHERE deleted_at IS NULL;

DROP TRIGGER IF EXISTS education_set_updated_at ON education;
CREATE TRIGGER education_set_updated_at
  BEFORE UPDATE ON education
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- website_visits
-- ยอดเข้าชม landing แบบรวมรายวัน (1 แถวต่อ 1 วัน)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS website_visits (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visit_date   DATE         NOT NULL,
  visit_count  BIGINT       NOT NULL DEFAULT 0
                 CHECK (visit_count >= 0),
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  CONSTRAINT website_visits_visit_date_uidx UNIQUE (visit_date)
);

COMMENT ON TABLE  website_visits IS 'ยอดเข้าชม personal website รวมรายวัน';
COMMENT ON COLUMN website_visits.id IS 'PK';
COMMENT ON COLUMN website_visits.visit_date IS 'วันที่นับยอด (1 แถวต่อ 1 วัน)';
COMMENT ON COLUMN website_visits.visit_count IS 'จำนวนครั้งที่เข้าชมในวันนั้น';
COMMENT ON COLUMN website_visits.created_at IS 'เวลาสร้างแถว';
COMMENT ON COLUMN website_visits.updated_at IS 'เวลาแก้ไขล่าสุด (อัปเดตเมื่อเพิ่มยอด)';

CREATE INDEX IF NOT EXISTS website_visits_visit_date_idx
  ON website_visits (visit_date DESC);

DROP TRIGGER IF EXISTS website_visits_set_updated_at ON website_visits;
CREATE TRIGGER website_visits_set_updated_at
  BEFORE UPDATE ON website_visits
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

COMMIT;
